services:

# PostgreSQL database container - user Domain
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
      POSTGRES_DB: user_db
    volumes:
      - user-db-data:/var/lib/postgresql/data #store data on host to persist
      - ./init-scripts/user-db:/docker-entrypoint-initdb.d # import database schema
    ports:
      - "5433:5432"
    networks:
      - invoice-net
    restart: unless-stopped

# Spring Boot user-service container - user Service
  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8090" 
    depends_on:
      - user-db  
    networks:
      - invoice-net
    restart: unless-stopped
    environment: #override service yml config for prod env variable
     SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user_db
     SPRING_DATASOURCE_USERNAME: user
     SPRING_DATASOURCE_PASSWORD: userpass


networks:
  invoice-net:
    driver: bridge
# Named volume for PostgreSQL persistence
volumes:
  user-db-data: