server:
    port: 8090
spring:
  # Spring app name
  application:
    name: company 
  # Database config
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/company_db
    username: ${DB_USER:user}
    password: ${DB_PASS:userpass}
  # Hibernate 
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: 5367566859703373367639792F423F452848284D6251655468576D5A71347437
app:
  cors:
    allowed-origins: "http://localhost:4200,https://myfrontend.com"
