server:
    port: 8091
spring:
    application:
        name: user
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/auth_db
        username: ${DB_USER:user}
        password: ${DB_PASS:userpass}
    jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
    jwt:
      secret: 5367566859703373367639792F423F452848284D6251655468576D5A71347437
      expiration-ms: 1800000